### ISSUE TITLE
Feature request: resize direction based on mouse position

### ISSUE THREAD

**Issue by roelvangils** [pablopunk/SwiftShift#40]
What if... the app would resize from the corner matching your mouse pointer's position when you press the shortcut keys for the Resize function?

![20240226_222238_Paper@2x](https://github.com/pablopunk/SwiftShift/assets/103744/17a312ca-fd39-4551-a922-ec4105bd0d5d)

- Quadrant 1: resize from the top-left
- Quadrant 2: resize from the top-right
- Quadrant 3: resize from the bottom-left
- Quadrant 4: resize from the bottom-right

**Comment by pablopunk** [comment]
That's really interesting, it could be a great solution to https://github.com/pablopunk/SwiftShift/issues/21

**Comment by roelvangils** [comment]
> That's really interesting, it could be a great solution to #21

Indeed! I think it will feel much more natural than adding more modifier key combinations to achieve the same thing. And there's no other app that implements window resizing it this way. So I hope you're going to do it! 😁

**Comment by roelvangils** [comment]
I was curious about your progress with the app. It holds so much promise, and I'm excited to see how it develops!

**Comment by pablopunk** [comment]
@roelvangils Hey, I actually gave it a try a while ago and kind of got a very clunky solution working.

The problem is that in order to resize a window programmatically, you need to specify the origin (top-left) and the new size (bottom-right). This works really well for the current behavior because it's just moving the bottom-right all the time. However, resizing from any other quadrant means moving the window and resizing at the same time, which made it very laggy and not a good experience at all.

I didn't find a workaround for that. I'm not sure if there's any; I'm not a Swift/macOS expert. But I'll leave this issue open in case anyone bumps into it and knows how to solve it.

**Comment by roelvangils** [comment]
@pablopunk hm I get it! 🙂 Thanks for trying! I have no idea how to do it either 😁 It would be nice if someone could up wit ha solution. But since no other similar app does this, it might just be impossible.

**Comment by roelvangils** [comment]
@pablopunk I found this [app](https://github.com/dmarcotte/easy-move-resize). It works a bit different than your app (you need to click in the window, which i don't want) and it doesn't work as smooth. But it does have the feature where you the mouse position inside the windows determines from which side you can start resizing it. Maybe you can get some inspiration from the source code 😁

**Comment by roelvangils** [comment]
Iti s so nice to see that you have added this functionality to the app! It works exactly as I imagined. Thanks and good luck with the development of the app!

<img width="320" alt="Screenshot" src="https://github.com/pablopunk/SwiftShift/assets/103744/b6757064-66ae-4ddc-835c-6adb4296b473">

Also, the word _quadrant_ sounds so sophisticated. I like it that you kept it! 🙂

**Comment by pablopunk** [comment]
@roelvangils thanks! Honestly in my mind I think of "cuadrantes" in Spanish so I was glad it worked on English too 😅

**Comment by pablopunk** [comment]
Released in [0.25.0](https://github.com/pablopunk/SwiftShift/releases/tag/0.25.0)
